services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5010:5010"

  frontend:
    build:
      context: ./client
      args:
        - VITE_API_URL=16.171.147.109:5010/api
    container_name: frontend
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
