services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5010:5010"

  frontend:
    build:
      context: ./client
      args:
        - VITE_API_URL:"http://16.171.147.109:5010"
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

deploy:
  needs: build-and-lint
  if: github.event_name == 'push'
  runs-on: ubuntu-latest
  steps:
    - name: Checkout (optional)
      uses: actions/checkout@v4

    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}

    - name: Write SSH key
      run: |
        echo "${EC2_KEY}" > ec2_key.pem
        chmod 600 ec2_key.pem
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}

    - name: Deploy on EC2 (git pull + docker compose up -d --build)
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_APP_DIR: ${{ secrets.EC2_APP_DIR }}
      run: |
        ssh -i ec2_key.pem ${EC2_USER}@${EC2_HOST} << EOF
          set -e
          cd "${EC2_APP_DIR}"

          git fetch --all
          git reset --hard origin/main

          docker compose up -d --build

          docker image prune -f

          docker compose ps
        EOF
